### ISSUE TITLE
URL open error

### ISSUE THREAD

**Issue by sakuyamaij** [alexskc/line-stickerbot#4]
Hello.
I am a Python beginner and try to understand this code.
When I ran this bot, after give a stricker url.
Error happend with

> 
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    send_stickers(stickerpage)
  File "main.py", line 51, in send_stickers
    dl_stickers(page)
  File "main.py", line 37, in dl_stickers
    response = urllib.request.urlopen(imageurl)
  File "E:\Python3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python3\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "E:\Python3\lib\urllib\request.py", line 489, in _open
    'unknown_open', req)
  File "E:\Python3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "E:\Python3\lib\urllib\request.py", line 1324, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: "https>
<
But I just use urllib to request other HTTPS page and it works.
I can't find the problem.

**Comment by AlicesReflexion** [comment]
Sorry for such a long delay. It should be fixed now.
